

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      # 한번에 업로드 할수 있는 최대 사이즈
      max-request-size: 30MB


  datasource: #내장 메모리 db를 사용하기위해 주소 설정
    url: jdbc:h2:mem:db   # jdbc:h2:tcp://localhost/~/typewriter
    username: sa
    password: "1234"
    driver-class-name: org.h2.Driver
  h2: #스프링부트에 내장 데이터 베이스 사용
    console:
      enabled: true #콘솔 활성화
      path: /h2-console #웹 콘솔 주소 예(127.0.0.1:8080/h2-console) 기본으로 외부 ip접근은 막고 있다

  ai:
    openai:
      api-key: 
      chat.options.model: gpt-4o
      chat.options.temperature: 0 #창의 성



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  application:
    name: unityServer
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8080



# 업로드 사이즈 제한 (하나의 사이즈)


# save img
files_dir: /home/cjftn/my_files/ #\\home\\cjftn\\IdeaProjects\\unityServer\\src\\main\\resources\\files\\ #//home//cjftn//IdeaProjects//unityServer//src//main//resources//files//
#my_files: /home/cjftn/IdeaProjects/unityServer/src/main/resources/files/

filedir: /home/cjftn/IdeaProjects/unityServer/src/main/resources/files/
